# This workflow will generate a ROCK install ISO weekly or on-demand with Actions.

name: Create ROCK ISO

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 7 * * mon' # every monday at 1am local


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel          
jobs:
  createiso:
    runs-on: self-hosted
    name: createiso

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout Repository
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v2
        with:
          ref: actions-centos
          
      - name: Checking runner requirements
        run: echo "checking local requirements" # local iso / git / ansible / etc

      - name: Bootstrap to install dependencies
        run: echo "running bootstrap"
      
      - name: Execute master ISO script
        run: echo "running master_iso"
      
      - name: Generate checksums
        run: echo "generating checksums"
      
      - name: Upload artifacts to webserver
        run: echo "uploading files"      
